[project]
name = "virtue_code_eval"
version = "0.1.0"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.ruff]
extend-exclude = ["virtue_code_eval/data/safety/redcode/"]