canary_exploit:
  task_name: reasoning/exploitation
  num_data: -1
  enabled: true
  subtasks:
    language: [ "python", "cpp" ]
    challenge_type: [ "constraint_satisfaction", "memory_corruption" ]
  metrics:
    - metric_name: execution
      config:
        method: canary_exploit